### ISSUE TITLE
`using` recognition?

### ISSUE THREAD

**Issue by PlaidPhantom** [atom/language-csharp#91] opened 2017-01-22 08:18 UTC
Hi, not sure if this is an issue for you or not, if it's in some other package feel free to send me on.

I've noticed a problem with the `using` statement on the first line of a file.  There seems to be some sort of non-printing character there; hitting backspace removes it and fixes this issue. my guess would be a byte-order mark?  So far this seems to happen in any C# file created in Visual Studio.

![image](https://cloud.githubusercontent.com/assets/678150/22181048/bb4ef792-e048-11e6-8985-180ccf642479.png)

**Comment by damieng** [comment] 2017-01-22 08:31
Duplicate of https://github.com/atom/language-csharp/issues/76

This has been fixed in the language-csharp package and is fixed on Atom 1.14 currently in Beta.

**Closed by damieng** 2017-01-22 08:31 UTC
